# Generated by Django 5.0.4 on 2024-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
