# Generated by Django 5.0.4 on 2024-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommercepost',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='exchangepost',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='birth_day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
