# Generated by Django 5.0.4 on 2024-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
