# Generated by Django 5.0.4 on 2024-05-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_base", "0002_exchangepost_is_paused"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_base.productcategory",
            ),
        ),
    ]
