# Generated by Django 5.0.4 on 2024-05-08 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_base", "0002_alter_affiliate_birth_day_alter_affiliate_dni_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ecommercepost",
            old_name="tittle",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="exchangepost",
            old_name="tittle",
            new_name="title",
        ),
    ]
