# Generated by Django 5.0.4 on 2024-05-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_exchange_exchange_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_base.branches'),
        ),
    ]
