# Generated by Django 5.0.4 on 2024-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_rename_tittle_ecommercepost_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepost',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
