# Generated by Django 5.0.4 on 2024-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_exchangepost_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ecommercepost',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangepost',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
