# Generated by Django 5.0.4 on 2024-05-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_base", "0003_exchange_deleted_alter_exchange_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exchangepost",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
