# Generated by Django 5.0.4 on 2024-05-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_alter_exchange_timestamp'),
        ('data_base', '0003_alter_products_product_category'),
    ]

    operations = [
    ]
