# Generated by Django 5.0.4 on 2024-05-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='ejemplo',
            field=models.IntegerField(default=0),
        ),
    ]
