# Generated by Django 5.0.4 on 2024-05-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0004_affiliate_points_alter_ecommercepost_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affiliate_Product',
            new_name='Affiliate_Need_Product',
        ),
    ]
