# Generated by Django 5.0.4 on 2024-05-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0004_affiliate_ejemplo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='ejemplo',
        ),
    ]
