# Generated by Django 5.0.4 on 2024-05-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0005_remove_affiliate_ejemplo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepost',
            name='ej',
            field=models.BooleanField(default=False),
        ),
    ]
