# Generated by Django 5.0.4 on 2024-05-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0006_exchangepost_ej'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangepost',
            name='ej',
        ),
    ]
